### ISSUE TITLE
Repo @universe/address-parser deleted?

### ISSUE THREAD

**Issue by cya** [universe/releases#1]
I noticed that the @universe/address-parser repository was deleted a few days ago. I was using this package in one of my projects, and I’m wondering if there’s any specific reason for the deletion.
[@universe/address-parser on npm](https://www.npmjs.com/package/@universe/address-parser)

Is there a plan to reintroduce the package, or is there a recommended alternative?

Thank you for any information you can provide!

**Comment by amiller-gh** [comment]
@cya sorry for the delay, I'm very happy to hear someone else is using it!

I don't think @universe/address-parser was ever a public repo, but not for any particular reason – we first developed it in a private mono-repo, and it's lived there ever since.

I'm more than happy to pull it out to a public repository though! Theres definitely room for improvement, and public contributions, but we do plan to continue maintaining it. Give me a day or so, and I'll drop the link here when it's public.

As for alternatives, there are not many other address parsers out there, and certainly none that I know of in the JS world that don't call out to a paid API, or with the level of address part detail our package implements.

**Comment by amiller-gh** [comment]
@cya Ended up tackling it tonight 🙂 

Public repo can now be found here: https://github.com/universe/address-parser

`@universe/address-parser@4.0.0` is the first version published from this public repo. I bumped the major version to denote the transition – there are no actual API changes between `3.0.0` and `4.0.0`.
